name: mirror

on:
  - push
  - delete

jobs:
  gitlab:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Sync to GitLab
      uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: ${{ vars.GITLAB_URL }}
        target-username: ${{ vars.GITLAB_USERNAME }}
        target-token: ${{ secrets.GITLAB_TOKEN }}
